# Generated by Django 3.2.3 on 2021-05-31 19:56

from django.db import migrations, models
import django.db.models.deletion
import midia.validators


class Migration(migrations.Migration):

    dependencies = [
        ('midia', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='link_video',
            new_name='video_url',
        ),
        migrations.RemoveField(
            model_name='albumimage',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='albumimage',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='audio',
            name='file',
        ),
        migrations.RemoveField(
            model_name='image',
            name='image_album',
        ),
        migrations.RemoveField(
            model_name='video',
            name='video',
        ),
        migrations.AddField(
            model_name='albumaudio',
            name='is_public',
            field=models.CharField(choices=[('ARQUIVAR', 'Arquivar'), ('PUBLICAR', 'Publicar')], default='Arquivar', max_length=20),
        ),
        migrations.AddField(
            model_name='albumvideo',
            name='is_public',
            field=models.CharField(choices=[('ARQUIVAR', 'Arquivar'), ('PUBLICAR', 'Publicar')], default='Arquivar', max_length=20),
        ),
        migrations.AddField(
            model_name='audio',
            name='audio_album',
            field=models.FileField(default=1, upload_to=midia.validators.UploadToPath('audios'), validators=[midia.validators.validate_file_size]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='document',
            name='is_public',
            field=models.CharField(choices=[('ARQUIVAR', 'Arquivar'), ('PUBLICAR', 'Publicar')], default='Arquivar', max_length=20),
        ),
        migrations.AddField(
            model_name='image',
            name='album',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='midia.albumimage'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='author',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
