# Generated by Django 3.2.3 on 2021-05-28 13:25

from django.db import migrations, models
import midia.validators


class Migration(migrations.Migration):

    dependencies = [
        ('midia', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='audio',
            old_name='file',
            new_name='audio_album',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='image',
            new_name='images',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='link_video',
            new_name='video_album',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='video',
            new_name='videos',
        ),
        migrations.AlterField(
            model_name='image',
            name='image_album',
            field=models.FileField(upload_to=midia.validators.UploadToPath('images')),
        ),
    ]
