# Generated by Django 3.2.3 on 2021-05-20 12:51

from django.db import migrations, models
import midia.validators


class Migration(migrations.Migration):

    dependencies = [
        ('midia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to='documents', validators=[midia.validators.validate_file_size]),
        ),
    ]
