# Generated by Django 3.2.3 on 2021-05-20 22:06

from django.db import migrations, models
import midia.validators


class Migration(migrations.Migration):

    dependencies = [
        ('midia', '0002_alter_document_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='file',
            field=models.FileField(upload_to='audios', validators=[midia.validators.validate_file_size]),
        ),
    ]
