# Generated by Django 3.2.3 on 2021-05-31 19:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import midia.validators


class Migration(migrations.Migration):

    dependencies = [
        ('midia', '0002_auto_20210531_1656'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='user.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video',
            name='album',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='midia.albumvideo'),
        ),
        migrations.AddField(
            model_name='video',
            name='author',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='user.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='albumimage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to=midia.validators.UploadToPath('documents'), validators=[midia.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to=midia.validators.UploadToPath('images')),
        ),
    ]
