# Generated by Django 3.2.3 on 2021-07-04 02:20

from django.db import migrations, models
import midia.validators


class Migration(migrations.Migration):

    dependencies = [
        ('midia', '0002_document_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='audio',
            field=models.FileField(upload_to=midia.validators.UploadToPath('audios'), validators=[midia.validators.validate_file_size], verbose_name='Fazer upload de áudio'),
        ),
        migrations.AlterField(
            model_name='audio',
            name='description',
            field=models.CharField(max_length=250, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to=midia.validators.UploadToPath('documents'), validators=[midia.validators.validate_file_size], verbose_name='Documento'),
        ),
        migrations.AlterField(
            model_name='image',
            name='description',
            field=models.CharField(max_length=250, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(max_length=50, verbose_name='Cor da tag'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Título da tag'),
        ),
        migrations.AlterField(
            model_name='video',
            name='description',
            field=models.CharField(max_length=250, verbose_name='Descrição'),
        ),
    ]
