# Generated by Django 3.2.3 on 2021-05-31 20:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('midia', '0003_auto_20210531_1656'),
    ]

    operations = [
        migrations.RenameField(
            model_name='audio',
            old_name='audio_album',
            new_name='audio',
        ),
        migrations.RemoveField(
            model_name='audio',
            name='audios',
        ),
        migrations.AddField(
            model_name='audio',
            name='album',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='audios', to='midia.albumaudio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='audio',
            name='author',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='audio',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='audios', to='user.user'),
            preserve_default=False,
        ),
    ]
