# Generated by Django 3.2.3 on 2021-06-01 11:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('midia', '0004_auto_20210531_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albumaudio',
            name='is_public',
            field=models.CharField(choices=[('ARQUIVAR', 'Arquivar'), ('PUBLICAR', 'Publicar')], default='Arquivar', max_length=20, verbose_name='Status de publicação'),
        ),
        migrations.AlterField(
            model_name='albumaudio',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='albumaudio',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AlterField(
            model_name='albumimage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums_images', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='albumvideo',
            name='is_public',
            field=models.CharField(choices=[('ARQUIVAR', 'Arquivar'), ('PUBLICAR', 'Publicar')], default='Arquivar', max_length=20, verbose_name='Status de publicação'),
        ),
        migrations.AlterField(
            model_name='albumvideo',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='albumvideo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AlterField(
            model_name='audio',
            name='author',
            field=models.CharField(max_length=100, verbose_name='Autor do álbum'),
        ),
        migrations.AlterField(
            model_name='audio',
            name='tags',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='midia.tag', verbose_name='Tags do álbum'),
        ),
        migrations.AlterField(
            model_name='audio',
            name='title',
            field=models.CharField(max_length=250, verbose_name='Título do álbum'),
        ),
        migrations.AlterField(
            model_name='document',
            name='is_public',
            field=models.CharField(choices=[('ARQUIVAR', 'Arquivar'), ('PUBLICAR', 'Publicar')], default='Arquivar', max_length=20, verbose_name='Status de publicação'),
        ),
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='document',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AlterField(
            model_name='image',
            name='author',
            field=models.CharField(max_length=100, verbose_name='Autor do álbum'),
        ),
        migrations.AlterField(
            model_name='image',
            name='tags',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='midia.tag', verbose_name='Tags do álbum'),
        ),
        migrations.AlterField(
            model_name='image',
            name='title',
            field=models.CharField(max_length=250, verbose_name='Título do álbum'),
        ),
        migrations.AlterField(
            model_name='video',
            name='author',
            field=models.CharField(max_length=100, verbose_name='Autor do álbum'),
        ),
        migrations.AlterField(
            model_name='video',
            name='tags',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='midia.tag', verbose_name='Tags do álbum'),
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(max_length=250, verbose_name='Título do álbum'),
        ),
    ]
