# Generated by Django 3.2.3 on 2021-05-30 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('midia', '0004_auto_20210528_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='albumaudio',
            name='is_public',
            field=models.CharField(choices=[('ARQUIVAR', 'Arquivar'), ('PUBLICAR', 'Publicas')], default='Arquivar', max_length=20),
        ),
        migrations.AddField(
            model_name='albumimage',
            name='is_public',
            field=models.CharField(choices=[('ARQUIVAR', 'Arquivar'), ('PUBLICAR', 'Publicas')], default='Arquivar', max_length=20),
        ),
        migrations.AddField(
            model_name='albumvideo',
            name='is_public',
            field=models.CharField(choices=[('ARQUIVAR', 'Arquivar'), ('PUBLICAR', 'Publicas')], default='Arquivar', max_length=20),
        ),
        migrations.AddField(
            model_name='document',
            name='is_public',
            field=models.CharField(choices=[('ARQUIVAR', 'Arquivar'), ('PUBLICAR', 'Publicas')], default='Arquivar', max_length=20),
        ),
    ]
