# Generated by Django 3.2.3 on 2021-05-30 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('midia', '0005_auto_20210530_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albumaudio',
            name='is_public',
            field=models.CharField(choices=[('ARQUIVAR', 'Arquivar'), ('PUBLICAR', 'Publicar')], default='Arquivar', max_length=20),
        ),
        migrations.AlterField(
            model_name='albumimage',
            name='is_public',
            field=models.CharField(choices=[('ARQUIVAR', 'Arquivar'), ('PUBLICAR', 'Publicar')], default='Arquivar', max_length=20),
        ),
        migrations.AlterField(
            model_name='albumvideo',
            name='is_public',
            field=models.CharField(choices=[('ARQUIVAR', 'Arquivar'), ('PUBLICAR', 'Publicar')], default='Arquivar', max_length=20),
        ),
        migrations.AlterField(
            model_name='document',
            name='is_public',
            field=models.CharField(choices=[('ARQUIVAR', 'Arquivar'), ('PUBLICAR', 'Publicar')], default='Arquivar', max_length=20),
        ),
    ]
