# Generated by Django 3.2.3 on 2021-05-22 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('midia', '0006_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='audio',
            old_name='name',
            new_name='title',
        ),
    ]
