# Generated by Django 3.2.3 on 2021-06-04 23:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import midia.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('midia', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exposure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título da exposição')),
                ('legend', models.CharField(max_length=200, verbose_name='Legenda da exposição')),
                ('content', models.CharField(max_length=200, verbose_name='Descrição exposição')),
                ('is_public', models.CharField(choices=[('ARQUIVAR', 'Arquivar'), ('PUBLICAR', 'Publicar')], default='Arquivar', max_length=20, verbose_name='Status de publicação')),
                ('thumbnail', models.ImageField(upload_to=midia.validators.UploadToPath('thumbail_exposure'))),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('album_audio', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='midia.albumaudio', verbose_name='Álbum de áudio')),
                ('album_image', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='midia.albumimage', verbose_name='Álbum de imagem')),
                ('album_video', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='midia.albumvideo', verbose_name='Álbum de video')),
                ('tags', models.ManyToManyField(to='midia.Tag')),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Usuários')),
            ],
            options={
                'verbose_name': 'Exposições',
                'verbose_name_plural': 'Exposições',
            },
        ),
    ]
