# Generated by Django 3.2.3 on 2021-05-31 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('midia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exposure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('legend', models.CharField(max_length=200)),
                ('content', models.CharField(max_length=200)),
                ('is_public', models.CharField(choices=[('ARQUIVAR', 'Arquivar'), ('PUBLICAR', 'Publicar')], default='Arquivar', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('album_audio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='midia.albumaudio')),
                ('album_image', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='midia.albumimage')),
                ('album_video', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='midia.albumvideo')),
                ('tags', models.ManyToManyField(to='midia.Tag')),
            ],
            options={
                'verbose_name': 'Exposições',
                'verbose_name_plural': 'Exposições',
            },
        ),
    ]
