# Generated by Django 3.2.3 on 2021-05-25 00:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exposure', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exposure',
            options={'verbose_name': 'Exposições', 'verbose_name_plural': 'Exposições'},
        ),
        migrations.AddField(
            model_name='exposure',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.user'),
            preserve_default=False,
        ),
    ]
