# Generated by Django 3.2.3 on 2021-05-22 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('midia', '0006_image'),
        ('exposure', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioAlbum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('audios', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='album_audio', to='midia.audio')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DocumentAlbum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('documents', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='album_document', to='midia.document')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Exposure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=50)),
                ('legend', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=250)),
                ('audio_album', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='exposure.audioalbum')),
                ('document_album', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='exposure.documentalbum')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ImageAlbum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('images', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='album_image', to='midia.image')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='VideoAlbum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exposure.tag')),
                ('videos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='album_video', to='midia.video')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='file',
            name='files',
        ),
        migrations.DeleteModel(
            name='Batch',
        ),
        migrations.DeleteModel(
            name='File',
        ),
        migrations.AddField(
            model_name='imagealbum',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exposure.tag'),
        ),
        migrations.AddField(
            model_name='exposure',
            name='image_album',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='exposure.imagealbum'),
        ),
        migrations.AddField(
            model_name='exposure',
            name='tags',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exposure_tags', to='exposure.tag'),
        ),
        migrations.AddField(
            model_name='exposure',
            name='video_album',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='exposure.videoalbum'),
        ),
        migrations.AddField(
            model_name='documentalbum',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exposure.tag'),
        ),
        migrations.AddField(
            model_name='audioalbum',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exposure.tag'),
        ),
    ]
