# Generated by Django 3.2.3 on 2021-05-22 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exposure', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='batch',
            old_name='owner',
            new_name='user',
        ),
    ]
