# Generated by Django 3.2.3 on 2021-05-22 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exposure', '0002_auto_20210522_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exposure',
            name='audio_album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exposure.audioalbum'),
        ),
        migrations.AlterField(
            model_name='exposure',
            name='document_album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exposure.documentalbum'),
        ),
        migrations.AlterField(
            model_name='exposure',
            name='image_album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exposure.imagealbum'),
        ),
        migrations.AlterField(
            model_name='exposure',
            name='video_album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exposure.videoalbum'),
        ),
    ]
