# Generated by Django 3.2.3 on 2021-06-01 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('midia', '0004_auto_20210531_1742'),
        ('exposure', '0002_exposure_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exposure',
            name='album_audio',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='midia.albumaudio'),
        ),
        migrations.AlterField(
            model_name='exposure',
            name='album_image',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='midia.albumimage'),
        ),
        migrations.AlterField(
            model_name='exposure',
            name='album_video',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='midia.albumvideo'),
        ),
    ]
