# Generated by Django 3.2.3 on 2021-05-30 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('midia', '0004_auto_20210528_1049'),
        ('exposure', '0003_auto_20210530_1734'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exposure',
            old_name='user',
            new_name='users',
        ),
        migrations.RemoveField(
            model_name='exposure',
            name='tags',
        ),
        migrations.AddField(
            model_name='exposure',
            name='tags',
            field=models.ManyToManyField(to='midia.Tag'),
        ),
    ]
