# Generated by Django 3.2.3 on 2021-05-22 23:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exposure', '0003_auto_20210522_2051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exposure',
            name='video_album',
        ),
        migrations.AddField(
            model_name='videoalbum',
            name='video_album',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='exposure.exposure'),
            preserve_default=False,
        ),
    ]
