# Generated by Django 3.2.3 on 2021-05-30 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exposure', '0004_auto_20210530_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='exposure',
            name='is_public',
            field=models.CharField(choices=[('ARQUIVAR', 'Arquivar'), ('PUBLICAR', 'Publicar')], default='Arquivar', max_length=20),
        ),
    ]
