# Generated by Django 3.2.3 on 2021-05-23 00:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exposure', '0004_auto_20210522_2054'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='mediaas/')),
                ('default', models.BooleanField(default=False)),
                ('width', models.FloatField(default=100)),
                ('length', models.FloatField(default=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='documentalbum',
            name='documents',
        ),
        migrations.RemoveField(
            model_name='documentalbum',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='exposure',
            name='audio_album',
        ),
        migrations.RemoveField(
            model_name='exposure',
            name='document_album',
        ),
        migrations.RemoveField(
            model_name='exposure',
            name='image_album',
        ),
        migrations.RemoveField(
            model_name='exposure',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='videoalbum',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='videoalbum',
            name='video_album',
        ),
        migrations.RemoveField(
            model_name='videoalbum',
            name='videos',
        ),
        migrations.RemoveField(
            model_name='imagealbum',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='imagealbum',
            name='images',
        ),
        migrations.RemoveField(
            model_name='imagealbum',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='imagealbum',
            name='title',
        ),
        migrations.RemoveField(
            model_name='imagealbum',
            name='updated_at',
        ),
        migrations.DeleteModel(
            name='AudioAlbum',
        ),
        migrations.DeleteModel(
            name='DocumentAlbum',
        ),
        migrations.DeleteModel(
            name='Exposure',
        ),
        migrations.DeleteModel(
            name='VideoAlbum',
        ),
        migrations.AddField(
            model_name='product',
            name='album',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='model', to='exposure.imagealbum'),
        ),
        migrations.AddField(
            model_name='image',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='exposure.imagealbum'),
        ),
    ]
