# Generated by Django 3.2.3 on 2021-05-23 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('midia', '0007_rename_name_audio_title'),
        ('exposure', '0006_auto_20210522_2117'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlbumImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('images', models.FileField(upload_to='images/')),
                ('album', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='midia.image')),
                ('tags', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exposure.tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='postimage',
            name='post',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='PostImage',
        ),
    ]
