# Generated by Django 3.2.3 on 2021-05-23 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exposure', '0007_auto_20210522_2132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='albumimage',
            name='images',
        ),
    ]
