# Generated by Django 3.2.3 on 2021-05-23 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exposure', '0008_remove_albumimage_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='albumimage',
            name='images',
            field=models.FileField(default=1, upload_to='images/'),
            preserve_default=False,
        ),
    ]
