# Generated by Django 3.2.3 on 2021-05-23 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exposure', '0009_albumimage_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exposure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('legend', models.CharField(max_length=200)),
                ('content', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('album_image', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='exposure.albumimage')),
                ('tags', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exposure.tag')),
            ],
        ),
    ]
