# Generated by Django 3.2.3 on 2021-06-04 22:42

from django.db import migrations, models
import midia.validators


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image_profile',
            field=models.ImageField(default=1, upload_to=midia.validators.UploadToPath('image_profile_user')),
            preserve_default=False,
        ),
    ]
