# Generated by Django 3.2.3 on 2021-07-04 02:20

from django.db import migrations, models
import midia.validators


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image_profile',
            field=models.ImageField(upload_to=midia.validators.UploadToPath('image_profile_user'), verbose_name='Iamgem de perfil'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Nome'),
        ),
    ]
